# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest
steps:
- script: java -version
- script:  mvn -v
#- checkout: self
- task: SynopsysSecurityScan@1
  inputs:
    scanType: 'polaris'
    bridge_polaris_serverUrl: 'https://poc.polaris.synopsys.com'
    bridge_polaris_accessToken: 's4jpgckfat47f3dcaebrc486lgmkikhai2pkb3dahsoecu1tg9c25v3smatn2u8nirve6eaa48k7u'
    bridge_polaris_application_name: 'kyleh'
    bridge_polaris_project_name: 'AzureIssueTest-1'
    bridge_polaris_assessment_types: 'SAST,SCA'
    bridge_polaris_branch_name: '$(Build.SourceBranchName)'
