trigger:
- develop

pool:
  vmImage: ubuntu-latest
resources:
  repositories:
    - repository: AzureBoardsScript
      ref: master
      type: git
      name: Implementations
steps:
- checkout: self
- bash: |
    curl -fLsS -o bridge.zip $BRIDGECLI_LINUX64 && unzip -qo -d $(Agent.TempDirectory) bridge.zip && rm -f bridge.zip
    $(Agent.TempDirectory)/synopsys-bridge --verbose --stage polaris \
      polaris.assessment.types='SAST,SCA' \
      polaris.application.name='KyleH' \
      polaris.project.name='ADO-BashTest' \
      polaris.branch.name=Bash
  env:
    BRIDGE_POLARIS_ACCESSTOKEN: $(BRIDGE_POLARIS_ACCESSTOKEN)
- checkout: AzureBoardsScript
- task: CmdLine@2
  inputs:
    script: |
     ls 
     python AzureBoardsScript/polaris_azure_ci.py -config "polaris-azure.conf" --polaris-application-name "kyleh" --polaris-project-name "AzureIssueTest-2" --polaris-branch-name $(Build.SourceBranchName) --polaris-severities-filter "''''critical'''',''''high'''',''''medium'''',''''low'''',''''info''''" --azure-project-name "PolarisTickets" --azure-iteration-path "iteration 2" --azure-area-path "area path test"

#- task: PythonScript@0
#  inputs:
#    scriptSource: 'filePath'
#    scriptPath: 'Implementations/AzureBoardsScript/polaris_azure_ci.py'
#    arguments: '--config "polaris-azure.conf" --polaris-application-name "kyleh" --polaris-project-name "AzureIssueTest-2" --polaris-branch-name $(Build.SourceBranchName) --polaris-severities-filter "''''critical'''',''''high'''',''''medium'''',''''low'''',''''info''''" --azure-project-name "PolarisTickets" --azure-iteration-path "iteration 2" --azure-area-path "area path test"'
#    workingDirectory: '/home/vsts/work/1/s/AzureBoardsScript/'
#- script: cat /home/vsts/work/1/s/AzureBoardsScript/logs/synopsys-azure.log
#  condition: always()